# ansi_tty colors for Kitty

background #1c1917
foreground #c2b8a3
selection_background #3a3228
selection_foreground #ebdbb2
url_color #5fafd7
cursor #c2b8a3

# Tabs
active_tab_background #1c1917
active_tab_foreground #d75f5f
inactive_tab_background #1c1917
inactive_tab_foreground #c2b8a3
tab_bar_background #1c1917

# normal
color0 #1c1917
color1 #d75f5f
color2 #87af87
color3 #d7af5f
color4 #5f87af
color5 #af87af
color6 #5fafaf
color7 #c2b8a3

# bright
color8 #6f6a60
color9 #ff875f
color10 #afd787
color11 #ffd787
color12 #5fafd7
color13 #d7afd7
color14 #87d7d7
color15 #ebdbb2

# extended colors
color16 #d7875f
color17 #af5f5f
